import { connect, setActive, execCommand } from '../src/cli.mjs';
await connect();
await setActive('Windows-7-7601');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
await execCommand('!combo win+r');
await sleep(1500);
await execCommand('!type cmd');
await sleep(500);
await execCommand('!key enter');
await sleep(2000);
await execCommand('!combo ctrl+alt+del');
await sleep(1500);
await execCommand('!combo win+d');
await sleep(1500);
console.log('CHORD-OK');
process.exit(0);
